sudo: required
services:
  - docker

before_install:
  - docker build -t jf971m/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jf971m/react-test npm test -- --coverage

after_success:
  - docker build -t jf971m/multi-client ./client
  - docker build -t jf971m/multi-nginx ./nginx
  - docker build -t jf971m/multi-server ./server
  - docker build -t jf971m/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push jf971m/multi-client
  - docker push jf971m/multi-nginx
  - docker push jf971m/multi-server
  - docker push jf971m/multi-worker


# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-286595124720
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY